### ISSUE TITLE
Default sensor orientation is off by 180 degrees

### ISSUE THREAD

**Issue by NullVoxPopuli** [MotoLab/Cleanflight-MotoLab#1]
in target.h:

    #define GYRO
    #define USE_GYRO_MPU6050

    #define GYRO_MPU6050_ALIGN CW180_DEG

    #define ACC
    #define USE_ACC_MPU6050

    #define ACC_MPU6050_ALIGN CW180_DEG

the default alignment is already off by180 degrees, so maybe this is why I was having issues?

maybe this means that there needs to be a 180 degree offset so that the alignment configuration can be correct in the UI?

**Comment by NullVoxPopuli** [comment]
I've been talking with some cleanflight people, and they said that based on my board setup, I'd need to set the gyro align to CW180_DEG_FLIP https://github.com/cleanflight/cleanflight/blob/master/docs/Cli.md

`set align_gyro=7`

I'll test this tonight.

**Comment by NullVoxPopuli** [comment]
Well, now they're saynig that maybe I just needed to rotate -180 degrees in the configurator, this issue might be closed. haha.

**Comment by MotoLab** [comment]
That depends on the actual orientation of the gyro IC on the PCB. It's
correct for normal upright orientation, at least.


Note that the github repo doesn't have my current code yet. I'll get it
updated asap, but the day job is interfering right now.

**Comment by NullVoxPopuli** [comment]
Yeah. silly day jobs. I want to test all the new info I have on board alignment altering. haha.

But yeah, currently, I think if I can get the board working properly via the gui, then there is no issue. Someone suggested that I could try -180 degrees on the roll axis.. I hadn't thought of trying negative rotations yet. -180 and 180 are the same, except they have different yaw behavior - so I think that could be what I need.

**Comment by NullVoxPopuli** [comment]
Logging results here:
 - 180 Roll has the same wiggle.
 - align_acc and align_gyro set to 7 (CW180_DEG_FLIP) with board alignment all 0s - pitch and roll controls are backwards in the 3d model. Same wiggle.
 - align_acc and align_gyro set to 7 (CW180_DEG_FLIP) with pitch and roll at 180 in board alignment. 3d model behaves correctly. Same wiggle.
 - align_acc and align_gyro set to 7 (CW180_DEG_FLIP) with pitch at 180 and roll at -180 in board alignment. 3d model behaves correctly. Same Wiggle
 - align_acc and align_gyro set to 7 (CW180_DEG_FLIP) with pitch at -180 and roll at -180 in board alignment. 3d model behaves correctly. Same Wiggle
 - align_acc and align_gyro set to 7 (CW180_DEG_FLIP) with pitch at -180, roll at -180, and yaw at 180 in board alignment. 3d model behaves correctly except yaw is backwards. Same Wiggle

**Comment by NullVoxPopuli** [comment]
Also tried align_acc and align_gyro set to 5 (CW0_DEG_FLIP) with all board alignments at 0. 3d model behaves correctly. but the yaw wiggle still exists

**Comment by NullVoxPopuli** [comment]
setting  yaw_direction / yaw_motor_direction to -1 fixed the yaw problem. Now I just need to figure out which of these configurations allows my roll/pitch attitude correction to be correct.

**Comment by NullVoxPopuli** [comment]
I figured out the problem, and the people in #cleanflight verified that it makes sense.

Because the PDB in integrated to the FC, the motors are also flipped. Which is why I'm having so many problems.

Motors 4 and 2 are flipped with 1 and 3.

Normally when a person flips the board, they just flip the board, and solder the ESCs to the correct locations on their FC. but on my quad the motors are also flipped. 

So, good news, is that this has nothing to do with your code! :-)
bad news is that I may need to fork cleanflight once you get your stuff merged and implement CLI-based fix.

**Comment by MotoLab** [comment]
I haven't pushed the latest source to github yet, but here's a binary.

This version has the MPU6050 interrupt enabled. It runs the loop as soon as
the int happens and ignores the looptime setting. With gyro_lpf=256, the
ints are 8khz, so the looptime is as low as the cpu can go, like setting
looptime=0 in the old code. With gyro_lpf at any other setting, the 6050
interrupts at 1khz so the indicated looptime is around 1000 uS.

**Comment by NullVoxPopuli** [comment]
that's awesome! :-)
I don't see an attachment though. :-\ I don't know if attachments work through github email.

anywho, my most recent scenario has me writing my own motor mixing... which caused the board to bork (it just beeps via buzzer indefinitely). a new something to flash with would be very much appreciated. :-)

**Comment by MotoLab** [comment]
I'll send it direct, what's your email?

**Comment by NullVoxPopuli** [comment]
LPSego3+motof3@gmail.com :-)
